def test_imports():
    import fastapi_client.api.pet_api
    import fastapi_client.api.store_api
    import fastapi_client.api.user_api
    import fastapi_client.api_client
    import fastapi_client.auth
    import fastapi_client.exceptions
    import fastapi_client.models
    import fastapi_client.password_flow_client
